name: Test Docker Build

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distro: [humble, jazzy, kilted]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        build-args: |
          ROS_DISTRO=${{ matrix.ros_distro }}
        push: false
        tags: phntm/bridge-client:test-${{ matrix.ros_distro }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
